###  -*-Makefile-*-
# Copyright (c) 2018-2019 Bluespec, Inc. All Rights Reserved

# ================================================================

BSC_COMP_FLAG1 = -Xcpp '-D OPTION1'
# BSC_COMP_FLAG1 = -Xcpp '-D OPTION2'
# BSC_COMP_FLAG1 = -Xcpp '-D OPTION3'
# BSC_COMP_FLAG1 = -Xcpp '-D OPTION4'

include ../Resources/Include_Makefile.mk
